### ISSUE TITLE
Error building with Qt Creator

### ISSUE THREAD

**Issue by sarimabbas** [PavelNajman/ProjectorLeapMotionCalibration#1]
I am using macOS 10.14.3 Qt Creator 4.8.2, Qt 5.12.1

I dragged the `Leap.h` and `LeapMath.h` header files from the SDK `include` folder into the root folder of this repository. 

When building, I get the following error message:

```
12:55:13: Running steps for project LeapCalibration...
12:55:13: Configuration unchanged, skipping qmake step.
12:55:13: Starting: "/usr/bin/make" -j4
ld: warning: directory not found for option '-L/lib/x64/'
ld: library not found for -lLeap
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [LeapCalibration.app/Contents/MacOS/LeapCalibration] Error 1
12:55:18: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project LeapCalibration (kit: Desktop Qt 5.12.1 clang 64bit)
When executing step "Make"
12:55:18: Elapsed time: 00:05.
```

I am a newcomer to Qt, so would appreciate your help. I am excited about replicating your project. Thank you.

<img width="1372" alt="Screen Shot 2019-03-14 at 1 03 19 PM" src="https://user-images.githubusercontent.com/3000809/54376518-9fe30600-4659-11e9-991b-58f4121c2716.png">

**Comment by PavelNajman** [comment]
Looks like your linker cannot find Leap Motion library. To fix your problem, you should create a LEAP_SDK environment variable with a path to the Leap Motion SDK directory or edit LIBS variable in LeapMotionCalibration.pro file directly.
